### ISSUE TITLE
Can not open aragon DAO UI any more on xdai / 1hive

### ISSUE THREAD

**Issue by merowingz** [1Hive/aragon#24]
1. Please go to: https://aragon.1hive.org/#/rcktstrsv2/
2. Meta Mask does not connect any more.
3. Error message dropped:

An unexpected error has occurred

[ethjs-rpc]  error with payload {"id":3109533381410,"jsonrpc":"2.0","params":[{"to":"0xaafca6b0c89521752e559650206d7c925fd0e530","data":"0x0178b8bff517506267c534f34fafeac155659ac2b8b2f380124731f019bd05e027994a63"},"latest"],"method":"eth_call"} Error: connection not open
in L
in k
in f
in p
in i
in a
in f
in pr
in Unknown
in _r
in v
in y
in i
in w
in u
in u
in div
in a
in h
in Provider
in y
in B
in i

**Comment by merowingz** [comment]
This is urgent as we can not access our voting and ETH in the vault any more.

**Comment by merowingz** [comment]
@0xGabi @fabriziovigevani @lkngtn  - Can anyone of you please help us here?
What do you suggest ?

**Comment by 0xGabi** [comment]
Hey @merowingz this should be fixed now. You may need to reset your browser cache or configure the Settings -> Ethereum node to: wss://rpc.gnosischain.com/wss
