### ISSUE TITLE
Some apps without contentURI break aragon client and cli

### ISSUE THREAD

**Issue by sembrestels** [1Hive/aragon#3]
**Describe the bug**
The apps view of some DAOs can be fetched. They may also break the apm cli.

**Mainnet or testnet?**
It happens on some xDAI DAOs.

**Organization**
This is an example: https://aragon.1hive.org/#/0x1d7ac94b1713e17bfa2e1c96d832329b4b79b404/apps/

**To Reproduce**
1. Go to the DAO Apps section
2. Open the console with F12
3. See the following error:

```
Uncaught Error: The parameter must be a valid HEX string.
    at c (index.js:170)
    at l (repo.js:48)
    at async a (repo.js:15)
    at async n.project (index.js:668)
```

**Expected behavior**
The apps should appear in the screen.

**Additional context**
If we debug it, we see that when calling [`getRepoVersionById`](https://github.com/aragon/aragon.js/blob/3a334947a0042f5fa8812c13ce20646d8bcf03c4/packages/aragon-wrapper/src/core/apm/repo.js#L45) we have an unhandled exception when we have a repo that has an empty contentURI.

That's exactly what happens with the app deployed in [0xabE9...37eb](https://blockscout.com/poa/xdai/address/0xabE9b53FEE0613D1aE1D318C7915b23C672037eb) on xDAI, it return a null contentURI, which throws an exception when is treated by this function.

In order to fix this issue, we can do one of these two things:
1. Fork the aragon.js repo and build the aragon client with this patched version.
2. Update the problematic app(s) in APM, so they don't cause this error anymore.

**Comment by Bitcoinera** [comment]
Guess it makes more sense to update the problematic apps in APM? Then it would always work, no matter what aragon.js version
